### ISSUE TITLE
Proxy should be able to run without ORY_ACCESS_TOKEN

### ISSUE THREAD

**Issue by xvello** [ory/cli#113]
**Is your feature request related to a problem? Please describe.**

The `ory proxy` commands require passing a valid `ORY_ACCESS_TOKEN` command. In the current state of the project, tokens have broad administrative rights and require handling as security-sensitive secrets.

Looking at the proxy code, this token is only used to retrieve the Ory Cloud project slug, which is not sensitive information (it is displayed in the email validation and password recovery emails you send).

**Describe the solution you'd like**

Similar to the [React Native integration](https://www.ory.sh/docs/start-building/native-mobile-app#react-native), the proxy should allow users to pass the project slug instead of a token. Either:

- via a new `--project` CLI flag, that will the used by `proxy.getEndpointURL` in lieu of calling `remote.GetProjectSlug`
- by changing the handling of the `--api-endpoint` flag to allow passing a full endpoint URL. This would also allow to remove [the context-based hack](https://github.com/xvello/ory-cli/blob/e0c51d4ef27d30e245bc6046540b5aaec5ded4a2/cmd/cloud/proxy/common.go#L439-L441) introduced for the unit tests

**Describe alternatives you've considered**

If a token will be necessary for planned proxy features, an alternative would be to allow creating an unprivileged token class, that does not have administrative access to the identity database.

**Comment by aeneasr** [comment]
You're absolutely right! It would be much better to just have the ORY_SDK_URL there. We actually do not use the access token for anything other than lookup up the slug!
