### ISSUE TITLE
Proxy should provide a `/.ory/init/logout` endpoint

### ISSUE THREAD

**Issue by xvello** [ory/cli#114]
**Is your feature request related to a problem? Please describe.**

Initiating the logout flow is non-trivial as we need to redirect the user to a URL with a unique token to start the flow. Doing so is not described in the Cloud documentation, but from [the Kratos documentation](https://www.ory.sh/kratos/docs/next/self-service/flows/user-logout/), it looks like one needs to request a logout token from Kratos, then build the logout URL from this token.

**Describe the solution you'd like**

Mirroring [the other init endpoints](https://www.ory.sh/docs/guides/proxy#url-structure), the proxy should provide a `/.ory/init/logout` endpoint that does the Kratos call and performs the http redirect to the right URL. This will make logout as easy as login (a simple static link).

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by aeneasr** [comment]
That would be a security issue as I could point any user to that endpoint to log them out. Making this explicit call ensures that you are not vulnerable to CSRF / DoS in this case.

Still needs some docs though :)

**Comment by xvello** [comment]
You are completely right, as the logout action does not require any confirmation by the user. My bad!

Can you please tell me whether [directly calling Kratos](https://www.ory.sh/kratos/docs/next/self-service/flows/user-logout/#self-service-logout-for-server-side-browser-applications) is the best way to retrieve the logout URL, or whether you have current/planned facilities to achieve that?

**Comment by aeneasr** [comment]
Yes, calling Kratos directly would be the best approach. Keep in mind that you want to go through the proxy though for that, so that the URLs and domains are all correct :)

**Comment by aeneasr** [comment]
I am closing this because we can not fix it :/

**Comment by xvello** [comment]
Agreed!
Maybe https://www.ory.sh/docs/guides/proxy/#url-structure could be updated to point to the kratos documentation? It will need an update anyway, to remove the `/.ory/init/` endpoints.

**Comment by aeneasr** [comment]
absolutely!

**Comment by aeneasr** [comment]
we’re changing the docs structure for cloud conpletely :)
