### ISSUE TITLE
Error: expected dialect to be one of [sqlite cockroach mysql postgres] but got: postgres

### ISSUE THREAD

**Issue by tristanls** [ory/cli#127]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/cli/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/cli/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

```
$ ory dev pop migration create -d=postgres ./persistence/sql/migrations/templates somename
Error: expected dialect to be one of [sqlite cockroach mysql postgres] but got: postgres
...
```

### Reproducing the bug

```
$ ory dev pop migration create -d=postgres ./persistence/sql/migrations/templates somename
Error: expected dialect to be one of [sqlite cockroach mysql postgres] but got: postgres
...
```

### Relevant log output

```shell
Error: expected dialect to be one of [sqlite cockroach mysql postgres] but got: postgres
```

### Version

0.1.0

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Other

### Additional Context

I'm pretty sure [`if stringslice.Has(supportedDialects, d)`](https://github.com/ory/cli/blob/79c87caf62c555f701891ece2bb72301a862dd1c/cmd/dev/pop/migration/create.go#L24) should be `if !stringslice.Has(supportedDialects, d)`

**Comment by aeneasr** [comment]
Nice find! :) PRs welcomed! :)

**Comment by tristanls** [comment]
#128
