### ISSUE TITLE
NPM, Brew and Docker can't install Ory CLI v0.1.0 on m1 MacOS Monterey

### ISSUE THREAD

**Issue by jknlsn** [ory/cli#131]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/cli/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/cli/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Running the given NPM, Brew or Docker install commands error out on my machine, m1 MacBook with macOS Monterey.

However the below Linux(?) script does work:
```
bash <(curl https://raw.githubusercontent.com/ory/meta/master/install.sh) -b . ory
```

### Reproducing the bug

Run:

```sh
npm i --save @ory/cli
brew install ory/tap/cli       
docker pull oryd/ory
```

### Relevant log output

```shell
npm i --save @ory/cli
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Users/jknlsn/node_modules/@ory/cli
npm ERR! command failed
npm ERR! command sh -c binwrap-install
npm ERR! ERR Error: Not Found: https://github.com/ory/cli/releases/download/v0.0.86/ory_0.0.86_macOS_64-bit.tar.gz
npm ERR!     at Request._callback (/Users/jknlsn/node_modules/binwrap/binstall.js:60:18)
npm ERR!     at Request.self.callback (/Users/jknlsn/node_modules/request/request.js:185:22)
npm ERR!     at Request.emit (events.js:376:20)
npm ERR!     at Request.<anonymous> (/Users/jknlsn/node_modules/request/request.js:1154:10)
npm ERR!     at Request.emit (events.js:388:22)
npm ERR!     at IncomingMessage.<anonymous> (/Users/jknlsn/node_modules/request/request.js:1076:12)
npm ERR!     at Object.onceWrapper (events.js:482:28)
npm ERR!     at IncomingMessage.emit (events.js:388:22)
npm ERR!     at endReadableNT (internal/streams/readable.js:1336:12)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:82:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jknlsn/.npm/_logs/2021-12-09T12_26_53_437Z-debug.log

brew install ory/tap/cli                                                     
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 4 taps (homebrew/cask-versions, homebrew/core, homebrew/cask and homebrew/services).
==> New Formulae
mist
==> Updated Formulae
Updated 40 formulae.
==> Updated Casks
Updated 39 casks.

==> Tapping ory/tap
Cloning into '/opt/homebrew/Library/Taps/ory/homebrew-tap'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 65 (delta 37), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (65/65), 15.93 KiB | 286.00 KiB/s, done.
Resolving deltas: 100% (37/37), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/ory/homebrew-tap/hydra.rb
formulae require at least a URL
Error: Cannot tap ory/tap: invalid syntax in tap!

docker pull oryd/ory
Using default tag: latest
latest: Pulling from oryd/ory
no matching manifest for linux/arm64/v8 in the manifest list entries
```

### Version

0.1.0

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Ory Cloud

### Additional Context

Trying to download 0.1.0 and connect to deployed Ory Cloud environment

**Comment by aeneasr** [comment]
Thank you for reporting! I can reproduce all of them. A couple of things to take away:

1. [ ] The linux script does indeed work on other platforms as well that support curl and unix shells
2. [ ] `docker pull --platform=linux/amd64 oryd/ory:v0.1.0` should work around the missing arm image for now. It's strange, I thought we had a release that addressed this but apparently not?!
3. [ ] Homebrew seems to fail because Ory Hydra does not have an ARM build yet but it's in the tap as well.
4. [ ] `@ory/cli` appears as if it's no longer being updated?

**Comment by jknlsn** [comment]
Great for the Linux script, that's good to know!

I actually can't get the Docker image to work on Linux either atm. Started a new VM, installed Docker and tried to run the oryd/ory image as per the instructions on the [Install Ory Proxy page here](https://www.ory.sh/docs/start-building/ory-cli-install-use#docker). So this didn't work:

```
docker pull oryd/ory
docker run --rm -it oryd/ory help
```

Ended up making a minimal image with Ory on it to run solely as a proxy, and have got that working now fine.

None of these are really deal-breakers, just make it a little more confusing for people to get started!

**Comment by aeneasr** [comment]
Totally agree, sorry for the bad experience! We'll be addressing all of these issues next week :)

**Comment by aeneasr** [comment]
Could you quickly say what error message you saw on the linux machine? Basically, all of these problems arise as we tried to add native ARM64 support for apple M1. It looks like I messed a couple of things up in the process...

**Comment by jknlsn** [comment]
Sure, so this is on a new Ubuntu 20,04 LTS VM.

```
snap install docker
docker pull oryd/ory
docker run --rm -it oryd/ory help
```

Which gives error:
`standard_init_linux.go:228: exec user process caused: no such file or directory`

**Comment by aeneasr** [comment]
Oh, interesting, that looks like our CGO library made it into the scratch container. Thank you!

**Comment by jknlsn** [comment]
When I was trying to build an Ory CLI image myself for using as a proxy I had issues when using an Alpine base image, which it looks like this Docker image might be doing from this: [https://github.com/ory/cli/blob/master/Dockerfile](https://github.com/ory/cli/blob/master/Dockerfile).

I got as far as these answers [https://askubuntu.com/questions/133389/no-such-file-or-directory-but-the-file-exists](https://askubuntu.com/questions/133389/no-such-file-or-directory-but-the-file-exists) and [https://serverfault.com/questions/883625/alpine-shell-cant-find-file-in-docker](https://serverfault.com/questions/883625/alpine-shell-cant-find-file-in-docker) before just using Ubuntu, which fixed it. 

Happy to share my dockerbuild file if that is helpful at all.

**Comment by aeneasr** [comment]
Docker fixed (arm64 added in next release):

```
$ docker pull --platform=linux/amd64 oryd/ory:v0.1.8
v0.1.8: Pulling from oryd/ory
Digest: sha256:2806c67603ee8b54737d780e237f4b90f98919d1cca379c0e466e662abd9f358
Status: Downloaded newer image for oryd/ory:v0.1.8
docker.io/oryd/ory:v0.1.8
$ docker pull --platform=linux/arm/v7 oryd/ory:v0.1.8
$ docker pull --platform=linux/arm/v6 oryd/ory:v0.1.8
```

Brew on M1:

```
brew install ory/tap/cli
```

Left to do:

1. npm (scheduled for 0.1.9)
2. docker arm64 (scheduled for 0.1.9)

**Comment by aeneasr** [comment]
https://www.npmjs.com/package/@ory/cli - fixed as well, docker arm64/v8 as well
