### ISSUE TITLE
Proxy does not store Ory Cloud session on Windows

### ISSUE THREAD

**Issue by Benehiko** [ory/cli#132]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/cli/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/cli/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

On Windows, it seems the proxy does not store the Kratos session correctly. This only happens on Windows and is not reproducible on Unix. 

See this discussion on Slack:
https://ory-community.slack.com/archives/C02MR4DEEGH/p1638541123026800

### Reproducing the bug

1. Install the cli on Windows 10
2. Run the proxy following the [Server-side app guide](https://www.ory.sh/docs/start-building/server-side-web-app/)
3. Go through the registration/login flow
4. Try access the `/protected` page
5. The node application asks to sign in again

### Version

v0.1.0

### On which operating system are you observing this issue?

Windows

**Comment by aeneasr** [comment]
It's quite unlikely that cookies work differently on Windows. I'm sure it's some other issue. Since we have revamped the guide now and use the process a bit differently, and the issue hasn't come up yet, I'm closing this for the time being.
