### ISSUE TITLE
Admin API calls such as `identities list` should be re-added

### ISSUE THREAD

**Issue by Benehiko** [ory/cli#152]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/cli/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/cli/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Commands listing identities in a project got removed in https://github.com/ory/cli/commit/2ad0459994016e836b2d9a56dab5e3a4ef25e095. We should re-add it.

### Reproducing the bug

Install the CLI and try run `ory identities list`. The command will not exist.

### Version

latest

**Comment by aeneasr** [comment]
Done
