### ISSUE TITLE
Support importing credentials through CLI

### ISSUE THREAD

**Issue by vinckr** [ory/cli#163]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/cli/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/cli/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We can import identities with 
https://www.ory.sh/docs/kratos/cli/kratos-identities-import
but no credentials.

### Describe your ideal solution

We can also import credentials through the CLI.

### Workarounds or alternatives

Use the Rest API: 
https://www.ory.sh/docs/kratos/reference/api#operation/adminCreateIdentity

### Version

latest

**Comment by aeneasr** [comment]
Have you tried importing credentials? It uses the same API and should just work!

**Comment by vinckr** [comment]
It works for the Kratos CLI but not the "Ory" CLI, uh if that makes sense.

**Comment by aeneasr** [comment]
Ah, that makes sense!

**Comment by aeneasr** [comment]
This is resolved now!
