### ISSUE TITLE
Ability to setup CORS using the cli proxy

### ISSUE THREAD

**Issue by Benehiko** [ory/cli#166]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/cli/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/cli/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

The `ory proxy` cannot set any CORS headers

### Describe your ideal solution

Add flags / environment variables that could be used to set CORS or even setup standard CORS headers so that the user would only need to provide the origins. We already have support for this feature in `ory/x` and would only need to add the cli flags.

### Workarounds or alternatives

none

### Version

v0.1.28

**Comment by aeneasr** [comment]
CORS is now available on the tunnel!

**Comment by aeneasr** [comment]
Done for CLI
