### ISSUE TITLE
Broken error message

### ISSUE THREAD

**Issue by tomekpapiernik** [ory/cli#169]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/cli/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/cli/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When I tried to update the Identity Service config with an unsupported value, I got an error message that was 960 lines long. 

### Reproducing the bug

1. Get Identity Service config and save it to a file. `ory get identity-config XXXXX --format yaml > identity-config.yaml`
2. Change `required_aal` to  `aal2`.
3. Save the file. 
4. `ory update identity-config XXXXXXX --file identity-config.yaml`
5. You get 960 lines of error

### Relevant log output

```shell
The request was malformed or contained invalid parameters
Unable to validate config: I[#] S[#/oneOf] oneOf failed
  I[#] S[#/oneOf/0] validation failed
    I[#] S[#/oneOf/0/allOf/0] allOf failed
      I[#] S[#/oneOf/0/allOf/0/required] missing properties: "version"
    I[#] S[#/oneOf/0/allOf/1] allOf failed
      I[#] S[#/oneOf/0/allOf/1/$ref] doesn't validate with "static://ory.cloud.schema.json#"
        I[#/session/whoami/required_aal] S[#/properties/session/properties/whoami/properties/required_aal/$ref] doesn't validate with "#/definitions/featureRequiredAal"
          I[#/session/whoami/required_aal] S[#/definitions/featureRequiredAal/enum] value must be one of "aal1", "highest_available"
  I[#] S[#/oneOf/1] validation failed
    I[#] S[#/oneOf/1/allOf/0] allOf failed
      I[#] S[#/oneOf/1/allOf/0/required] missing properties: "version"

and so on...
```

### Version

0.1.27

### On which operating system are you observing this issue?

Ory Cloud

### In which environment are you deploying?

Ory Cloud

**Comment by aeneasr** [comment]
Sorry, wrong ping!
