### ISSUE TITLE
Mirror external services as well

### ISSUE THREAD

**Issue by Benehiko** [ory/cli#188]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/cli/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/cli/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

When developing locally, some services might fall outside of the local environment, however, the cookie retrieved from Ory Cloud will be scoped to the Ory domain or CNAME domain which are translated to localhost with the `ory tunnel`. When we now communicate with external services we would need to pass along the cookie from the local environment and transform it back to the receiving domain to an external service, e.g Azure API Manager.

### Describe your ideal solution

Be able to set more upstream URLs to mirror and not just Ory Cloud. 

These upstream URLs should also translate the cookie from localhost to the original domain.

### Workarounds or alternatives

None

### Version

v0.1.36

### Additional Context

https://ory-community.slack.com/archives/C02MR4DEEGH/p1660033017459529

**Comment by aeneasr** [comment]
I read through the thread, it's an interesting question. Basically the problem arises when you run basically three services:

1. Local development system (e.g. a UI)
2. Remote development system (e.g. something on Heroku)
3. Ory Cloud

The problem is getting the credentials to the remote system while developing locally.

**Comment by aeneasr** [comment]
I don't really have a good solution for this at hand at the moment. It's a complex set of problems and it depends a bit on the use case. I do have some ideas, though - but they will require some time to manifest.

**Comment by richard-peters** [comment]
Thanks @aeneasr

**Comment by aeneasr** [comment]
The easiest solution would be to offer an API where you can exchange your session token / cookie for a JSON Web Token, probably. I had this in the back of my head for some time.

**Comment by aeneasr** [comment]
@richard-peters a potential workaround would be to set up a subdomain of the domain you use in Azure (so e.g. `local.myazuredomain.com`) which routes to 127.0.0.1, and then set up the ory tunnel to use that domain. It's a bit of effort to add a localhost rewrite for a domain (using e.g. `/etc/hosts`) and it's a bit different on every OS, but it is a workaround to get you unblocked :)

You can probably find how to do this on Stackoverflow for any OS flavor :)

**Comment by richard-peters** [comment]
@aeneasr this is the approach I've taken but I can't get it to work locally (I can see how it may work on a hosted staging instance) - the following will expose Ory APIs at //localhost:4000, which I don't think helps?

`ory tunnel --dev --project xx-xx-xx http://local.mydomain.com:3000`

**Comment by aeneasr** [comment]
If you check `ory help tunnel` it will show you different configs, one of them should be the one you need (it has two args iirc)

**Comment by richard-peters** [comment]
Would this need a custom domain added to Ory Cloud (with the same root domain) and for calls (via the tunnel) to Ory to be on `http://auth.mydomain.com:4000`?

**Comment by aeneasr** [comment]
No, it should all be doable in the Ory Tunnel completely:

```
ory tunnel  --dev --project xx-xx-xx  \
		http://local.mydomain.com:3000 \
		http://ory.mydomain.com:3000 \
		--cookie-domain example.org
```

With an `/etc/host` of:

```
127.0.0.1  local.mydomain.com
127.0.0.1  ory.mydomain.com
```

That *should* do it!

**Comment by richard-peters** [comment]
Many thanks, I'm able to hit my API with the Ory session cookies with the above configuration.
