### ISSUE TITLE
Provide command to manage pure SQL migrations

### ISSUE THREAD

**Issue by jonas-jonas** [ory/cli#223]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/cli/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/cli/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Context and scope

The Ory CLI provides a command to manage `fizz` migrations. However, in most projects, we moved away from fizz migrations and are now writing plain SQL files containing the migration SQL commands.

This design doc aims to describe a set of commands to manage these SQL migrations in Ory projects.

The names of SQL migration files in Ory projects typically follow a set schema. These names contain information about the time of the creation of the migration, as well as some context about the content of the migration. The schema is `YYYYMMDDHHmmSS000000_<name>.[engine.]up|down.sql`

For example:
The migration `20220926173820000000_recovery_code.up.sql` would be a migration created on the 26th, September 2022 at 17:38:20 (5:38:20 pm) and it contains SQL to create the table for recovery codes.

Additionally, the `up` part after the "name" of the migration indicates that the files contains the statements to execute the migration. 

Each migration also consists of another `down` version that should contain the statements to "undo" the migration (where possible). This is needed in case the change needs to be reverted and the state before the change needs to be restored.

Optionally, in most Ory projects, migrations can also be written to target a specific database engine. This is done by adding its identifier (e.g. `mysql`, `postgres`, `sqlite3` or `cockroach`) between the "name" of the migration, and it's "type" (`up` or `down`). So `20220926173820000000_recovery_code.mysql.up.sql` would only target MySQL databases.

### Goals and non-goals

Goals:
- Provide an easy-to-use way to manage and maintain SQL migrations over the course of the development of a feature/PR/etc.

Non-Goals:
- A testing environment for SQL migrations

### The design

Working with SQL migrations can be tedious and repetitive, so the SQL command should provide a set of commands to work with these migrations:

- A command to easily create new migration files with the current timestamp given a name
- A command to copy an existing migration to a specific database engine
- A command to update the timestamp of a specific migration to the current time (_very useful when working on larger codebases over a longer timespan, where the timestamp is outdated after a while_)

**Comment by aeneasr** [comment]
I would add that 0000 is a sequence number. Since some DBs can’t mix DDL and DSL statements in the same transaction, we need one file for DSL and one for DDL. So maybe add a flag of how many of these files we want?
