### ISSUE TITLE
The `--project` flag should accept both UUIDs and slugs

### ISSUE THREAD

**Issue by aeneasr** [ory/cli#267]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/cli/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/cli/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Apparently `ls identities` does not work with `--project <slug>` while other commands do.

### Reproducing the bug

```
 % ory ls identities --project very-cool-slug
No project selected! Please use the flag --project to specify one.
```

### Version

master

### Additional Context

Ory proxy seems to handle this correctly!

**Comment by CaptainStandby** [comment]
maybe related: #156
