### ISSUE TITLE
cannot use cli with SSO accounts

### ISSUE THREAD

**Issue by hyperknot** [ory/cli#294]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/cli/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/cli/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I signed up for Ory Network using Google sign-in. I cannot use ory auth, as it asks for password. 

### Reproducing the bug

Make an Ory account using Google sign-in. Try to use `ory auth`

### Version

Version:    v0.1.48

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Other

**Comment by CaptainStandby** [comment]
As a workaround you can log into the Ory Console and create a password to be used with the CLI.
Please have a look at the documentation: https://www.ory.sh/docs/guides/cli/cli-basics#accounts-with-social-sign-in

**Comment by aeneasr** [comment]
This is resolved now as the CLI now uses oauth2 to sign in via the browser!
