### ISSUE TITLE
ory delete identity command don't work

### ISSUE THREAD

**Issue by Sacramentix** [ory/cli#297]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/cli/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/cli/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When i run the command
`ory delete identity 0a345eb2-9e13-4862-8ad3-d0bd3e28187d --project nervous-wozniak-xhrj507314`
I get 
`No project selected! Please use the flag --project to specify one.`
Despite clearly having one project flag i get this and the command don't work.

### Reproducing the bug

1 run: ory delete identity _identity-id_ --project _project-id_

### Relevant log output

```shell
log:
`No project selected! Please use the flag --project to specify one.`
```

### Version

Version:    v0.2.1 Git Hash:   d1886fd9ec850e370c147a8ecb26f6e953943c9b Build Time: 2023-01-07T17:43:52Z

### On which operating system are you observing this issue?

Windows

### In which environment are you deploying?

None

**Comment by Sacramentix** [comment]
I've try to do it with quote bu it did not work
`ory delete identity "0a345eb2-9e13-4862-8ad3-d0bd3e28187d" --project "nervous-wozniak-xhrj507314"`

**Comment by Sacramentix** [comment]
Well i did not enter the project id but the project slug. it seems to work with the project id.
But the console output is cryptic. it should display that the project id is incorrect and when the command is successfull it should display that has been successfull instead of displaying `ID      0a345eb2-9e13-4862-8ad3-d0bd3e28187d`

**Comment by aeneasr** [comment]
You're right! We do have a commit though that will fix this behaviour. @tilschuenemann can you please confirm?

**Comment by tilschuenemann** [comment]
@Sacramentix 
This is implemented on master, see [here](https://github.com/ory/cli/commit/7b71d49fa9488623bd2341c37430f65d1bffb535).

A partial slug will also be enough to type as long as it's matching one project :)

**Comment by aeneasr** [comment]
Great, thank you @tilschuenemann - closing this. We'll release a new version of the Ory CLI soon
