### ISSUE TITLE
Any chance of getting BSD support?

### ISSUE THREAD

**Issue by ciresnave** [ory/cli#312]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/cli/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/cli/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I am running FreeBSD with Bash and the latest version of Go installed.  I would very much like to use the cli but the install script states "ory/ crit platform freebsd/amd64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/ory//issues/new".  Is there any chance of getting FreeBSD support added to the installer and the cli if it also lacks it?

Also, in the error message from the install script, it says to file a request at https://github.com/ory//issues/new.  That page doesn't exist.  I'm hoping it meant this repository.

Whether there's a possibility of adding support or not, thank you for your work.

### Describe your ideal solution

Ideally, I would like to be able to use the exact same commands under FreeBSD that I can on Linux.  Most *NIXs aren't terribly different so I am hoping adding BSD support wouldn't be much extra work.

### Workarounds or alternatives

I've considered pulling down the cli code and manually compiling it but the fact that the installer specifically states it isn't compatible with FreeBSD makes me leery to try it.

### Version

https://raw.githubusercontent.com/ory/meta/master/install.sh

**Comment by aeneasr** [comment]
We'd love to have FreeBSD supported! We disabled FreeBSD builds a while ago due to cross compile issues. Maybe they're resolved now? Fix would need to go into https://github.com/ory/xgoreleaser
