### ISSUE TITLE
Allow using the proxy/tunnel without temporary API keys

### ISSUE THREAD

**Issue by alnr** [ory/cli#362]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/cli/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/cli/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Follow-up to https://github.com/ory/cli/pull/359#discussion_r1671345624

### Describe your ideal solution

-

### Workarounds or alternatives

-

### Version

-

**Comment by nanvenomous** [comment]
Is this related to the latest changes of `ory proxy` which now opens a browser? if so I'm also running into this / could at least use a workaround for local development.

**Comment by aeneasr** [comment]
You now need to be signed into the Ory CLI, or you need a valid Project API Key. In the current release, there is still a bug preventing the proper use of the project api key - we'll fix that.

The project api key is needed to make social sign in work on the local domain!

**Comment by nanvenomous** [comment]
@aeneasr Thanks for clarifying. For my use case even a flag like `--skip-project-api-keys` would simplify local development when the proxy is necessary but maybe some of the cloud features are not. 

would this make sense in a new issue?

**Comment by ChrisSargent** [comment]
@aeneasr - we've updated to v1.0.1 but we're still being prompted to go through oauth flow with the api key set. Was this merged supposed to have fixed this?

<img width="959" alt="Screenshot 2024-10-16 at 21 54 57" src="https://github.com/user-attachments/assets/85809684-48f8-4ef2-8a55-21faeae909f2">

**Comment by aeneasr** [comment]
> @aeneasr Thanks for clarifying. For my use case even a flag like `--skip-project-api-keys` would simplify local development when the proxy is necessary but maybe some of the cloud features are not.
> 
> would this make sense in a new issue?

Yes please

**Comment by aeneasr** [comment]
> @aeneasr - we've updated to v1.0.1 but we're still being prompted to go through oauth flow with the api key set. Was this merged supposed to have fixed this?
> 
> <img alt="Screenshot 2024-10-16 at 21 54 57" width="959" src="https://private-user-images.githubusercontent.com/12176122/377212274-85809684-48f8-4ef2-8a55-21faeae909f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDc0MjIsIm5iZiI6MTcyOTE0NzEyMiwicGF0aCI6Ii8xMjE3NjEyMi8zNzcyMTIyNzQtODU4MDk2ODQtNDhmOC00ZWYyLThhNTUtMjFmYWVhZTkwOWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA2Mzg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YmRmMDJhOTZlM2M0Y2JjNThmZTA4ZWI5MGNiZWM0OWEzYTYxMWNmZTMyYTI2YzVjYzQ5Njg3NThjNmI1MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.soE-z7M-kl1Oi-bddEF-RGPA-ALTb1zXEGnizi7ufTM">

How did you set your project api key?

Also is the project api key from the project you are trying to proxy/tunnel?

**Comment by ChrisSargent** [comment]
> How did you set your project api key?

I created the api key using the Console UI

I tried several ways of 'setting' it. At first we have it being ran from an `execSync` command that we set the `env` field on. That didn't work so I tried setting it directly in front of the command as in the screenshot above.

```
ORY_PROJECT_API_KEY=ory_pat....... ory tunnel http://localhost:8000 --dev
```

> Also is the project api key from the project you are trying to proxy/tunnel?

Yes. Well, it's not really possible to do otherwise because if you try to set a `--project` flag, you get an "ORY_PROJECT_API_KEY and 'project' flag can't be both set, please remove one of them"

**Comment by aeneasr** [comment]
```
ORY_PROJECT_API_KEY=ory_pat....... ory tunnel http://localhost:8000 --dev -q
```

Will do the trick

**Comment by ChrisSargent** [comment]
thanks!
