### ISSUE TITLE
ory auth times out on Windows

### ISSUE THREAD

**Issue by jasonnutter** [ory/cli#372]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/cli/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/cli/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

After installing the `ory` CLI on Windows, `ory auth` returns `Error: failed to authenticate, please try again: context deadline exceeded` after completing authentication the opened browser in a reasonable amount of time.

### Reproducing the bug

1. Install ory CLI via scoop: https://www.ory.sh/docs/guides/cli/installation#windows
2. Run `ory auth` in new Powershell via Windows Terminal.
3. In the opened browser window (in my case, in Edge), complete authentication (I tested with both Google SSO and my account password) in a reasonable amount of time.
4. Observe success message in the browser window.
5. Return to the CLI to see `Error: failed to authenticate, please try again: context deadline exceeded`.

### Version

Version:    v1.0.0-alpha.1 Git Hash:   17c744dc094f16b7d23c9c4c3b33c1a489458500 Build Time: 2024-07-29T13:43:11Z

### On which operating system are you observing this issue?

Windows

### In which environment are you deploying?

None

**Comment by jasonnutter** [comment]
Follow up question: any plans to have this flow use the device code flow? Might make this more reliable.

**Comment by zepatrik** [comment]
This should be resolved with the v1.0.0-alpha.2 release. Can you confirm?

**Comment by jasonnutter** [comment]
Yes, works now. Thanks!
