### ISSUE TITLE
github.com/gobuffalo/fizz@v1.13.1-0.20200903094245-046abeb7de46: invalid version: unknown revision 046abeb7de46

### ISSUE THREAD

**Issue by christianskovholm** [ory/cli#43]
**Describe the bug**

go.mod references an unknown revision of the github.com/gobuffalo/fizz package, specifically: github.com/gobuffalo/fizz@v1.13.1-0.20200903094245-046abeb7de46. The latest seem to be v1.13.0.

**To Reproduce**

1. Clone this repo.
2. Build.

**Expected behavior**

A successful built without any dependency errors.

**Environment**

go version go1.15.6 linux/amd64

**Comment by aeneasr** [comment]
Thank you, this repository isn't really supposed to be built outside of the CI as it is primarily internally tooling. We'll fix it if the next CI build fails!
