### ISSUE TITLE
Broken dependency `github.com/oleiade/reflections`

### ISSUE THREAD

**Issue by johanforssell** [ory/cli#71]
**Describe the bug**

Cannot download dependencies because of checksum mismatch.

**To Reproduce**

```
~/ory > git clone git@github.com:ory/cli.git

~/ory/cli > cd cli

~/ory/cli > go list -m -json all

verifying github.com/oleiade/reflections@v1.0.0/go.mod: checksum mismatch
	downloaded: h1:rdFxbxq4QXVZWj0F+e9jqjDkc7dbp97vkRixKo2JR60=
	go.sum:     h1:RbATFBbKYkVdqmSFtx13Bb/tVhR0lgOBXunWTZKeL4w=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Expected behavior**

Dependencies should be downloaded and integrated.

**Environment**

- commit 9d1f4ea397ed11df045f40ad37a87c85473a0d8b (HEAD -> master, tag: v0.0.49, origin/master, origin/HEAD)
- MacOS Big Sur, 11.2.3
- go version go1.16.3 darwin/amd64
- go version go1.16.3 darwin/arm64 (_also_)

**Comment by aeneasr** [comment]
Resolved on master
